name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Instalar dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Iniciar análise SonarQube
        run: dotnet sonarscanner begin /k:"guilherme-martins92_fiap-order-service" /o:"guilherme-martins92" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.host.url="https://sonarcloud.io"

      - name: Compilar o projeto
        run: src/fiap-order-service.sln --no-incremental

      - name: Executar testes e coletar cobertura
        run: dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"

      - name: Finalizar análise SonarQube
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
